"""empty message

Revision ID: 0148e369fc8c
Revises: 84addf781ab1
Create Date: 2024-04-13 18:17:41.508781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0148e369fc8c'
down_revision = '84addf781ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targetlocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county1', sa.String(length=64), nullable=False),
    sa.Column('subcounty1', sa.String(length=64), nullable=False),
    sa.Column('county2', sa.String(length=64), nullable=False),
    sa.Column('subcounty2', sa.String(length=64), nullable=False),
    sa.Column('county3', sa.String(length=64), nullable=False),
    sa.Column('subcounty3', sa.String(length=64), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('targetlocs')
    # ### end Alembic commands ###
