"""empty message

Revision ID: 13f726a1a0d2
Revises: e8d52b1fe1ff
Create Date: 2024-06-26 05:13:09.102807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f726a1a0d2'
down_revision = 'e8d52b1fe1ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('matched_status')

    # ### end Alembic commands ###
