"""empty message

Revision ID: 4fc37ccbdf6d
Revises: 0fbabe68cade
Create Date: 2024-04-13 06:19:50.148902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc37ccbdf6d'
down_revision = '0fbabe68cade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currentinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('county', sa.String(length=64), nullable=False),
    sa.Column('subcounty', sa.String(length=64), nullable=False),
    sa.Column('teaching_level', sa.String(length=64), nullable=False),
    sa.Column('school_category', sa.String(length=64), nullable=True),
    sa.Column('school_type', sa.String(length=64), nullable=True),
    sa.Column('school_gender', sa.String(length=64), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currentinfo')
    # ### end Alembic commands ###
