"""empty message

Revision ID: 84addf781ab1
Revises: 4fc37ccbdf6d
Create Date: 2024-04-13 06:35:25.702351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84addf781ab1'
down_revision = '4fc37ccbdf6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currentinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_comb', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currentinfo', schema=None) as batch_op:
        batch_op.drop_column('subject_comb')

    # ### end Alembic commands ###
