"""empty message

Revision ID: e8d52b1fe1ff
Revises: 
Create Date: 2024-06-16 21:37:58.487540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d52b1fe1ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('pw_hash', sa.String(length=128), nullable=True),
    sa.Column('transfer_update_status', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_teachers_username'), ['username'], unique=True)

    op.create_table('currentinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('county', sa.String(length=64), nullable=False),
    sa.Column('subcounty', sa.String(length=64), nullable=False),
    sa.Column('teaching_level', sa.String(length=64), nullable=False),
    sa.Column('school_category', sa.String(length=64), nullable=True),
    sa.Column('school_type', sa.String(length=64), nullable=True),
    sa.Column('school_gender', sa.String(length=64), nullable=True),
    sa.Column('subject_comb', sa.String(length=64), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id')
    )
    op.create_table('targetlocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county1', sa.String(length=64), nullable=False),
    sa.Column('subcounty1', sa.String(length=64), nullable=False),
    sa.Column('county2', sa.String(length=64), nullable=False),
    sa.Column('subcounty2', sa.String(length=64), nullable=False),
    sa.Column('county3', sa.String(length=64), nullable=False),
    sa.Column('subcounty3', sa.String(length=64), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('targetlocs')
    op.drop_table('currentinfo')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_username'))
        batch_op.drop_index(batch_op.f('ix_teachers_email'))

    op.drop_table('teachers')
    # ### end Alembic commands ###
