"""empty message

Revision ID: e98077177198
Revises: 2064815131fa
Create Date: 2024-04-28 04:34:06.009840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98077177198'
down_revision = '2064815131fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targetlocs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targetlocs', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    # ### end Alembic commands ###
